### ISSUE TITLE
"export 'ɵBrowserPlatformLocation' was not found

### ISSUE THREAD

**Issue by Rofound** [F-loat/vue-cli-plugin-qiankun#11]
运行后报错，angular 无法显示页面
![image](https://user-images.githubusercontent.com/26542093/86332048-8285e100-bc7c-11ea-96fa-009218e47ed5.png)

**Comment by F-loat** [comment]
看起来和这个插件没什么关系？

**Comment by Rofound** [comment]
对不起，是我搞错了 这个 umijs 的 qiankun 项目报错的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "徒言"<notifications@github.com&gt;; 
发送时间: 2020年7月2日(星期四) 下午4:22
收件人: "F-loat/vue-cli-plugin-qiankun"<vue-cli-plugin-qiankun@noreply.github.com&gt;; 
抄送: "liupei"<1353590214@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [F-loat/vue-cli-plugin-qiankun] &quot;export &#39;&#x275;BrowserPlatformLocation&#39; was not found (#11)





 
看起来和这个插件没什么关系？
