### ISSUE TITLE
在对应子模块下刷新的问题

### ISSUE THREAD

**Issue by ZhengXiaowei** [F-loat/vue-cli-plugin-qiankun#2]
比如在`/foo-app`下刷新，那么浏览器就直接加载`foo-app`项目了，而不是通过我们的`portal`中去加载`foo-app`子模块了。

不刷新还好，一刷新，浏览器选择的入口就变了。

**Comment by F-loat** [comment]
fixed a62abb762ba41711a627f089725d339d8e130794

这个需要调整下 html 的 fallback 策略
