### ISSUE TITLE
有办法将已有的vue项目转化为主项目或者子项目吗？

### ISSUE THREAD

**Issue by canyuegongzi** [F-loat/vue-cli-plugin-qiankun#5]
有办法将已有的vue项目转化为主项目或者子项目吗？

**Comment by F-loat** [comment]
qiankun 接入的成本是很低的，具体改动可以参考[文档](https://qiankun.umijs.org/zh/guide/getting-started.html#%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B)，使用这个插件的话可以免去打包工具的配置

**Comment by F-loat** [comment]
已有项目也可以直接调用 `vue add vue-cli-plugin-qiankun` 的话，会进行一些转换，但可能还需要手动修改下
