### ISSUE TITLE
qiankun 2.x版本有实践么？

### ISSUE THREAD

**Issue by yangdengcheng** [F-loat/vue-cli-plugin-qiankun#8]
qiankun 2.x版本有实践么？

**Comment by yangdengcheng** [comment]
@F-loat 这边已经实践出qiankun 2.x的demo了，可以和你一起参与么？

**Comment by F-loat** [comment]
可以的，欢迎 pr

**Comment by F-loat** [comment]
我最近应该也会更新下

**Comment by F-loat** [comment]
看起来 2.x 的破坏性变动是比较少的，我这边只有一个全局变量需要改动，你们在更新到 2.x 版本时还有遇到什么问题吗

**Comment by yangdengcheng** [comment]
@F-loat 我今天重新初始化了一个主应用，两个子应用，然后在切换子应用的时候出现了问题。你可以尝试一下。说window.history.pushState报错。我现在正在看这个问题。

**Comment by yangdengcheng** [comment]
@F-loat 昨天我是用的该0.2.2版本的内容。本地调试跑代码都是没问题的。

**Comment by F-loat** [comment]
@yangdengcheng 这个项目的示例已经改成 2.0 版本的 qiankun 了，我这边没有遇到问题

https://f-loat.github.io/vue-cli-plugin-qiankun

**Comment by yangdengcheng** [comment]
@F-loat 已经提了PR。麻烦看一下。新版本在子应用切换的时候会报错。

**Comment by F-loat** [comment]
好了，examples 里面看着没这个问题，我待会儿发个小版本

**Comment by yangdengcheng** [comment]
@F-loat 加个wx？ 17399942222
